# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForclosureStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=512)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Foreclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('sale_date', models.DateField()),
                ('zip', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=128)),
                ('deed_of_trust_amount', models.FloatField()),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('zip', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('in_continuum_of_care', models.BooleanField()),
                ('in_shelter', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='foreclosure',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AddField(
            model_name='forclosurestatushistory',
            name='foreclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Foreclosure'),
        ),
    ]
