# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForclosureStatusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=512)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Foreclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512)),
                ('sale_date', models.DateField()),
                ('zip', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=128)),
                ('deed_of_trust_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('create_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('zip', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('in_continuum_of_care', models.BooleanField()),
                ('in_shelter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person_more_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status_type', models.IntegerField(choices=[(-1, ' '), (2, 'Divorced'), (1, 'Married'), (0, 'Unmarried')], default=-1, verbose_name='Marital status')),
                ('ethinicity_type', models.IntegerField(choices=[(-1, ' '), (0, 'caucasian'), (1, 'African American'), (2, 'Hispanic'), (3, 'Asian')], default=-1, verbose_name='Race')),
                ('family_size', models.IntegerField()),
                ('was_previously_homeless', models.BooleanField()),
                ('has_prior_criminal_record', models.BooleanField()),
                ('has_disabilities', models.BooleanField()),
                ('is_pregnant', models.BooleanField()),
                ('is_veteran', models.BooleanField()),
                ('in_employed', models.BooleanField()),
                ('has_mental_health_issues', models.BooleanField()),
                ('person_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person')),
            ],
        ),
        migrations.AddField(
            model_name='foreclosure',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Person'),
        ),
        migrations.AddField(
            model_name='forclosurestatushistory',
            name='foreclosure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Foreclosure'),
        ),
    ]
