# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person_more_details',
            name='person_link',
        ),
        migrations.AddField(
            model_name='person',
            name='ethinicity_type',
            field=models.IntegerField(choices=[(-1, ' '), (0, 'caucasian'), (1, 'African American'), (2, 'Hispanic'), (3, 'Asian')], default=-1, verbose_name='Race'),
        ),
        migrations.AddField(
            model_name='person',
            name='family_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='has_disabilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='has_mental_health_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='has_prior_criminal_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='in_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status_type',
            field=models.IntegerField(choices=[(-1, ' '), (2, 'Divorced'), (1, 'Married'), (0, 'Unmarried')], default=-1, verbose_name='Marital status'),
        ),
        migrations.AddField(
            model_name='person',
            name='was_previously_homeless',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Person_more_details',
        ),
    ]
