# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161022_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='create_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='deed_of_trust_amount',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='foreclosure',
            name='sale_date',
            field=models.DateField(null=True),
        ),
    ]
