# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161023_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreclosure',
            name='defendant',
            field=models.CharField(max_length=512),
        ),
    ]
