# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161023_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreclosure',
            old_name='defendant',
            new_name='name',
        ),
    ]
